Esqueci senha
DonRamon-Inc/game-collection-api pull request #24
Opened 2022-08-26 23:50 UTC by GiovanniPrado

## Template de Pull Request

### Checklist básica

- [ ] Todos os imports estão sendo usados
- [ ] Nenhum print de debug foi commitado
- [ ] Variáveis tem nomes compreensíveis porém simples
- [ ] Funções tem nomes compreensíveis porém simples
- [ ] As responsabilidades estão bem divididas (sem controller atuando como view)

2022-08-27 13:48 UTC, KleydsonGuilherme commented on app/models/usuario.py
> +  token_valido_ate = db.Column(db.DateTime, nullable = False)
Token não deveria ser "nullable = True"? tendo em vista que o esperado é que o mesmo seja null a maior parte do tempo.

2022-08-27 14:23 UTC, KleydsonGuilherme approved these changes
Ok, apenas um duvida na questão do Nullable no usuario.py

2022-08-27 16:37 UTC, Matheus-Campos requested changes

2022-08-27 16:37 UTC, Matheus-Campos commented on app/models/usuario.py
> +  def salvar_atualizar_senha(self, senha):
sugestão: não dá para colocar a lógica de gerar hash da senha dentro da função `salvar` já existente? Talvez usando um if para checar se a senha foi alterada ou não, se foi, gera um novo hash

2022-08-27 16:37 UTC, Matheus-Campos commented on app/models/usuario.py
> +  token_valido_ate = db.Column(db.DateTime, nullable = False)
Concordo, `token_valido_ate` deveria ser nullable

2022-08-29 14:17 UTC, Matheus-Campos commented on app/controllers/usuario_controller.py
> +    return "token válido"
Essa função deveria retornar um valor booleano, já que o token ou é válido ou não é

2022-08-31 16:52 UTC, RamonRCM approved these changes
Mudanças realizadas e comentários atendidos.

2022-08-31 16:53 UTC, RamonRCM approved these changes
Aprovado

2022-08-31 16:58 UTC, RamonRCM approved these changes
Resolvido

2022-08-31 17:33 UTC, Matheus-Campos1 approved these changes

2022-08-31 17:35 UTC, Matheus-Campos approved these changes

2022-08-31 17:59 UTC, merged