Recebimento steam
DonRamon-Inc/game-collection-api pull request #25
Opened 2022-08-28 22:38 UTC by KleydsonGuilherme

## Template de Pull Request

### Checklist básica

- [ ] Todos os imports estão sendo usados
- [ ] Nenhum print de debug foi commitado
- [ ] Variáveis tem nomes compreensíveis porém simples
- [ ] Funções tem nomes compreensíveis porém simples
- [ ] As responsabilidades estão bem divididas (sem controller atuando como view)

2022-08-29 03:09 UTC, Matheus-Campos requested changes

2022-08-29 03:09 UTC, Matheus-Campos commented on app/controllers/usuario_controller.py
>  def auth_steam():
Essa rota é protegida (precisa de autenticação) e portanto precisa do `@token_required`, dessa forma saberemos qual usuário quer integrar sua conta com a steam por que ele terá que passar o token.

2022-08-29 03:09 UTC, Matheus-Campos commented on app/controllers/usuario_controller.py
> +  if not usuario or not steam_id:
Se o `steam_id` não veio na request, nem precisaria consultar o usuário no banco. Sendo assim, melhor validar o body da request primeiro, se não tem tiver `steam_id`, já responde a chamada com erro 400 Bad Request. (Usar função validar_body pode ser uma boa) @RamonRCM

2022-08-29 03:09 UTC, Matheus-Campos commented on app/controllers/usuario_controller.py
> +  id_usuario_atual = body["id_usuario_atual"]
Mesmas coisas se aplicam aqui. O id do usuário vem do token de autenticação (usar `@token_required` nessa rota também)

2022-08-30 01:25 UTC, KleydsonGuilherme commented on app/controllers/usuario_controller.py
>  def auth_steam():
Feito.

2022-08-30 01:26 UTC, KleydsonGuilherme commented on app/controllers/usuario_controller.py
> +  if not usuario or not steam_id:
Feito usando validar_body

2022-08-30 01:26 UTC, KleydsonGuilherme commented on app/controllers/usuario_controller.py
> +  id_usuario_atual = body["id_usuario_atual"]
Feito.

2022-08-31 16:57 UTC, RamonRCM approved these changes
Aprovado, comentários resolvidos

2022-08-31 17:38 UTC, Matheus-Campos approved these changes

2022-08-31 21:36 UTC, merged