atualizando cadastro para modelo MVC
DonRamon-Inc/game-collection-api pull request #9
Opened 2022-06-30 23:49 UTC by GiovanniPrado

## Template de Pull Request

### Checklist

[ ] Variáveis tem nomes compreensíveis porém simples
[ ] Funções tem nomes compreensíveis porém simples
[ ] As responsabilidades estão bem divididas (sem controller atuando como view)

2022-07-09 01:51 UTC, Matheus-Campos requested changes

2022-07-09 01:51 UTC, Matheus-Campos commented on app/controllers/usuario_controller.py
> +  retornos_funcoes = [
Esse nome de variável não tá muito legal

2022-07-09 01:51 UTC, Matheus-Campos commented on app/app.py
> +from .models.db import db #..models.db?
Remover comentário

2022-07-09 01:51 UTC, Matheus-Campos commented on app/controllers/usuario_controller.py
> +from sqlalchemy import null
Remover import não usado

2022-07-09 01:51 UTC, Matheus-Campos commented on app/controllers/usuario_controller.py
> +def editar_usuario(request, id):
Esta função vai ser usada agora?

2022-07-09 01:51 UTC, Matheus-Campos commented on app/rotas.py
> +  @app.put("/usuarios/<id>")
Essa rota está fora do escopo dessa feature

2022-07-09 01:51 UTC, Matheus-Campos commented on app/rotas.py
> +  @app.post("/usuarios")
Eu mudaria essa rota para /cadastro

2022-07-09 01:53 UTC, Matheus-Campos commented on app/controllers/usuario_controller.py
> +                validar_email(body)
Arrumar isso aqui, padronizar os retornos das funções de validação, se uma retorna None, todas deveriam retornar None

2022-07-11 20:36 UTC, GiovanniPrado commented
Todas as pendências foram concluídas. Solicito uma nova avaliação.

2022-07-13 01:06 UTC, Matheus-Campos approved these changes
LGTM

2022-07-13 01:08 UTC, merged